//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariYeni.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public int SatisFiyati { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
